Use https: instead of git:
armPelionEdge/manifest-pelion-edge pull request #52
Opened 2021-02-19 13:18 UTC by JanneKiiskila

The repos are public and we know that invasive proxies or restrictive firewalls will block git clones using git@domain.

2021-02-19 13:19 UTC, JanneKiiskila commented
@ygoyal18  @x85446  @esajaa  - please review.

2021-02-19 16:13 UTC, ygoyal18 approved these changes

2021-02-22 08:36 UTC, JanneKiiskila commented
@ygoyal18 - merge then?

2021-02-22 11:06 UTC, esajaa requested changes

2021-02-22 11:06 UTC, esajaa commented on default.xml
> +    <remote name="yocto" fetch="https://git.yoctoproject.org" />
This does not work. Use `<remote name="yocto" fetch="https://git.yoctoproject.org/git/" />` instead

2021-02-22 11:06 UTC, esajaa commented
Also, this PR should probably be based on dev, not master

2021-02-22 11:46 UTC, JanneKiiskila commented
Ok, sounds like it's better to do new PR then.

2021-02-22 11:46 UTC, closed without merging

2021-02-22 11:47 UTC, JanneKiiskila commented on default.xml
> +    <remote name="yocto" fetch="https://git.yoctoproject.org" />
Same with OE, too? @esajaa

2021-02-22 13:25 UTC, JanneKiiskila commented
https://github.com/PelionIoT/manifest-pelion-edge/pull/53 replacing this one.